name: Master build

on:
  push:
    branches: [ "master" ]

jobs:
  clean:
    uses: tracefy/github-actions-workflows/.github/workflows/utilities-clean.yml@master
  test:
    needs:
      - clean
    uses: tracefy/github-actions-workflows/.github/workflows/python-test.yml@master
    secrets: inherit

  todo:
    needs:
      - clean
    uses: tracefy/github-actions-workflows/.github/workflows/utilities-todo.yml@master
    secrets: inherit